# Generated by Django 5.1.6 on 2025-03-31 08:11

import django.core.validators
import django.db.models.deletion
import job_portal.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=100)),
                ("employer", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("project_name", models.CharField(max_length=100)),
                ("summary", models.TextField(blank=True, null=True)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("project_link", models.URLField(blank=True, null=True)),
                ("github_link", models.URLField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-completion_date"],
            },
        ),
        migrations.CreateModel(
            name="JobInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("job_post", models.CharField(max_length=100)),
                ("job_description", models.TextField()),
                ("job_post_url", models.URLField(blank=True, null=True)),
                (
                    "ai_choice",
                    models.CharField(
                        choices=[("chatgpt", "ChatGPT"), ("gemini", "Gemini")],
                        default="chatgpt",
                        max_length=20,
                    ),
                ),
                (
                    "recruiter_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "recruiter_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("recruiter_linkedin", models.URLField(blank=True, null=True)),
                (
                    "reference_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "reference_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("reference_linkedin", models.URLField(blank=True, null=True)),
                (
                    "resume_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=job_portal.models.resume_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["pdf", "doc", "docx"]
                            )
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("resume_created", "Resume_Created"),
                            ("resume_keyword_created", "Resume_Keyword_Created"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Input",
                "verbose_name_plural": "Job Inputs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AIProcessingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("process_type", models.CharField(max_length=50)),
                ("status", models.CharField(max_length=20)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "job_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_logs",
                        to="job_portal.jobinput",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Keyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keyword", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("technical", "Technical Skill"),
                            ("soft", "Soft Skill"),
                            ("qualification", "Qualification"),
                            ("requirement", "Requirement"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("relevance_score", models.FloatField(default=1.0)),
                ("is_matched", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job_input",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="keywords",
                        to="job_portal.jobinput",
                    ),
                ),
            ],
            options={
                "ordering": ["-relevance_score"],
            },
        ),
        migrations.CreateModel(
            name="ExperienceBulletPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_points",
                        to="job_portal.experience",
                    ),
                ),
                (
                    "keywords",
                    models.ManyToManyField(blank=True, to="job_portal.keyword"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProjectBulletPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "keywords",
                    models.ManyToManyField(blank=True, to="job_portal.keyword"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bullet_points",
                        to="job_portal.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("mid_name", models.CharField(blank=True, max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=15)),
                ("address", models.TextField(blank=True, null=True)),
                ("linkedin", models.URLField(blank=True, null=True)),
                ("github", models.URLField(blank=True, null=True)),
                ("portfolio", models.URLField(blank=True, null=True)),
                (
                    "summary",
                    models.TextField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(100)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("uploaded", "Uploaded"),
                            ("generated", "Generated"),
                            ("failed", "Failed"),
                        ],
                        default="uploaded",
                        max_length=10,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="projects",
                to="job_portal.resume",
            ),
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language_name", models.CharField(max_length=100)),
                (
                    "proficiency",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                            ("native", "Native"),
                        ],
                        default="basic",
                        max_length=20,
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="languages",
                        to="job_portal.resume",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="experience",
            name="resume",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="experiences",
                to="job_portal.resume",
            ),
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("school_name", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=100)),
                ("degree", models.CharField(max_length=100)),
                (
                    "degree_type",
                    models.CharField(
                        choices=[
                            ("high_school", "High School"),
                            ("associate", "Associate Degree"),
                            ("bachelor", "Bachelor's Degree"),
                            ("master", "Master's Degree"),
                            ("doctorate", "Doctorate"),
                            ("other", "Other"),
                        ],
                        default="bachelor",
                        max_length=20,
                    ),
                ),
                ("field_of_study", models.CharField(max_length=100)),
                ("graduation_date", models.DateField(blank=True, null=True)),
                (
                    "gpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=3, null=True
                    ),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="educations",
                        to="job_portal.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-graduation_date"],
            },
        ),
        migrations.CreateModel(
            name="CustomData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Type of data (e.g., Achievements, Awards, Hobbies)",
                        max_length=100,
                    ),
                ),
                ("completion_date", models.DateField(blank=True, null=True)),
                (
                    "bullet_points",
                    models.TextField(
                        blank=True,
                        help_text="Add bullet points, one per line",
                        null=True,
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                (
                    "institution_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="custom_data",
                        to="job_portal.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-completion_date"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("institute", models.CharField(blank=True, max_length=100, null=True)),
                ("completion_date", models.DateField(blank=True, null=True)),
                ("expiration_date", models.DateField(blank=True, null=True)),
                ("score", models.CharField(blank=True, max_length=50, null=True)),
                ("link", models.URLField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certifications",
                        to="job_portal.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["-completion_date"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=50)),
                (
                    "skill_type",
                    models.CharField(
                        choices=[
                            ("technical", "Technical"),
                            ("soft", "Soft"),
                            ("language", "Language"),
                            ("tool", "Tool"),
                        ],
                        default="technical",
                        max_length=20,
                    ),
                ),
                ("proficiency_level", models.IntegerField(default=0)),
                (
                    "resume",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="job_portal.resume",
                    ),
                ),
            ],
            options={
                "ordering": ["skill_type", "-proficiency_level"],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="technologies",
            field=models.ManyToManyField(blank=True, to="job_portal.skill"),
        ),
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "api_name",
                    models.CharField(
                        choices=[("chatgpt", "ChatGPT"), ("gemini", "Gemini")],
                        max_length=20,
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("keyword_extraction", "Keyword Extraction"),
                            ("resume_parsing", "Resume Parsing"),
                            ("content_generation", "Content Generation"),
                            ("analysis", "Analysis"),
                        ],
                        max_length=50,
                    ),
                ),
                ("input_tokens", models.IntegerField(default=0)),
                ("output_tokens", models.IntegerField(default=0)),
                ("total_tokens", models.IntegerField(default=0)),
                (
                    "cost",
                    models.DecimalField(decimal_places=6, default=0.0, max_digits=10),
                ),
                (
                    "response_time",
                    models.FloatField(
                        default=0.0, help_text="API response time in seconds"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "Success"),
                            ("failed", "Failed"),
                            ("error", "Error"),
                        ],
                        default="success",
                        max_length=20,
                    ),
                ),
                ("error_message", models.TextField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("request_id", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "job_input",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to="job_portal.jobinput",
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "api_name", "timestamp"],
                        name="job_portal__user_id_e98d81_idx",
                    ),
                    models.Index(
                        fields=["api_name", "operation"],
                        name="job_portal__api_nam_d92e4b_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="job_portal__timesta_ee9684_idx"
                    ),
                ],
            },
        ),
    ]
